"""
Registre centralisé des sources de veille pour CIH Bank.
Périmètre PFE 2026: Régulateurs, Institutions, Presse Éco et Secteur Bancaire.
"""

SOURCES_REGISTRY = {
    # --- 1. RÉGULATEURS & INSTITUTIONS OFFICIELLES (MAROC) ---
    "bam_news": {
        "name": "Bank Al-Maghrib - Communiqués",
        "base_url": "https://www.bkam.ma/fr/Communiques",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "Communiqué",
        "article_link_selector": "h1.title a",
        "title_selector": "h1",
        "content_selector": "div.news-content, div.body-content",
        "use_browser": True,
    },
    "bam_circulaires": {
        "name": "Bank Al-Maghrib - Circulaires",
        "base_url": "https://www.bkam.ma/fr/Supervision-bancaire/Reglementation-et-conformite/Circulaires",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "Circulaire",
        "article_link_selector": "a.title",
        "title_selector": "h1",
        "content_selector": "div.news-content, div.body-content",
        "use_browser": True,
    },
    "ammc_news": {
        "name": "AMMC - Communiqués",
        "base_url": "https://www.ammc.ma/fr/actualites",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "Communiqué",
        "article_link_selector": "h2.title a",
        "title_selector": "h1.page-header",
        "content_selector": "div.content",
    },
    "me_news": {
        "name": "Ministère de l'Économie et des Finances",
        "base_url": "https://www.finances.gov.ma/fr/Pages/Actualites.aspx",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "News",
        "article_link_selector": "h2.title a",
        "title_selector": "h1",
        "content_selector": "div.content",
        "use_browser": True,
    },
    "cndp_news": {
        "name": "CNDP - Actualités",
        "base_url": "https://www.cndp.ma/fr/actualites.html",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "News",
        "article_link_selector": "div.item-block a",
        "title_selector": "h1",
        "content_selector": "div.content",
    },
    "sgg_news": {
        "name": "Secrétariat Général du Gouvernement",
        "base_url": "http://www.sgg.gov.ma/fr/Actualités.aspx",
        "category": "Régulateurs & Institutions Officielles",
        "doc_type": "News",
        "article_link_selector": "h2.title a",
        "title_selector": "h1",
        "content_selector": "div.content",
    },

    # --- 2. RÉGLEMENTATION INTERNATIONALE ---
    "bis_press": {
        "name": "Bank for International Settlements (BIS)",
        "base_url": "https://www.bis.org/press/index.htm",
        "category": "Réglementation Internationale",
        "doc_type": "Press Release",
        "article_link_selector": "a[href*='/press/p']",
        "title_selector": "h1.title",
        "content_selector": "div#cms-content",
    },
    "imf_news": {
        "name": "International Monetary Fund (IMF)",
        "base_url": "https://www.imf.org/en/news",
        "category": "Réglementation Internationale",
        "doc_type": "News",
        "article_link_selector": "a[href*='/en/news/articles/']",
        "title_selector": "h1",
        "content_selector": "div.news-content",
        "use_browser": True,
    },
    "world_bank_news": {
        "name": "World Bank",
        "base_url": "https://www.worldbank.org/en/news/all",
        "category": "Réglementation Internationale",
        "doc_type": "News",
        "article_link_selector": "a[href*='/en/news/press-release/']",
        "title_selector": "h1",
        "content_selector": "div.body-copy",
    },
    "eba_news": {
        "name": "European Banking Authority (EBA)",
        "base_url": "https://www.eba.europa.eu/news-press/news",
        "category": "Réglementation Internationale",
        "doc_type": "News",
        "article_link_selector": "div.news-item a",
        "title_selector": "h1",
        "content_selector": "div.node__content",
    },

    # --- 3. PRESSE ÉCONOMIQUE & FINANCIÈRE ---
    "leconomiste": {
        "name": "L'Economiste",
        "base_url": "https://www.leconomiste.com/actus",
        "category": "Presse Économique & Financière",
        "doc_type": "Articles",
        "article_link_selector": "h2.title a",
        "title_selector": "h1.title",
        "content_selector": "div.node-content",
    },
    "medias24_eco": {
        "name": "Medias24 - Économie",
        "base_url": "https://www.medias24.com/economie/",
        "category": "Presse Économique & Financière",
        "doc_type": "Articles",
        "article_link_selector": "h2.entry-title a",
        "title_selector": "h1.entry-title",
        "content_selector": "div.entry-content",
    },
    "challenge_ma": {
        "name": "Challenge.ma",
        "base_url": "https://www.challenge.ma/category/economie/",
        "category": "Presse Économique & Financière",
        "doc_type": "Articles",
        "article_link_selector": "h3.entry-title a",
        "title_selector": "h1.entry-title",
        "content_selector": "div.entry-content",
    },
    "reuters_finance": {
        "name": "Reuters Financials",
        "base_url": "https://www.reuters.com/business/finance/",
        "category": "Presse Économique & Financière",
        "doc_type": "News",
        "article_link_selector": "a[data-testid='Heading']",
        "title_selector": "h1",
        "content_selector": "div.article-body__content__17Yit",
        "use_browser": True,
    },

    # --- 4. SECTEUR BANCAIRE MAROC ---
    "cih_bank_news": {
        "name": "CIH Bank - Communiqués",
        "base_url": "https://www.cihbank.ma/actualite/banque",
        "category": "Secteur Bancaire Maroc",
        "doc_type": "Communiqué",
        "article_link_selector": "div.card a",
        "title_selector": "h1",
        "content_selector": "div.content",
    },
    "gpbm_news": {
        "name": "GPBM (Banques du Maroc)",
        "base_url": "https://www.gpbm.ma/actualites",
        "category": "Secteur Bancaire Maroc",
        "doc_type": "News",
        "article_link_selector": "h2.title a",
        "title_selector": "h1",
        "content_selector": "div.content",
    },
    "stock_exchange_news": {
        "name": "Bourse de Casablanca",
        "base_url": "https://www.casablanca-bourse.com/bourseweb/Actualites.aspx",
        "category": "Secteur Bancaire Maroc",
        "doc_type": "Market News",
        "article_link_selector": "h2.title a",
        "title_selector": "h1",
        "content_selector": "div.content",
        "use_browser": True,
    },
    "acaps_news": {
        "name": "ACAPS - Actualités",
        "base_url": "https://www.acaps.ma/fr/actualites",
        "category": "Secteur Bancaire Maroc",
        "doc_type": "News",
        "article_link_selector": "h2.title a",
        "title_selector": "h1",
        "content_selector": "div.content",
    },
}
